/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import javax.swing.ImageIcon;

/**
 *
 * @author TOHA
 */
public class AboutPanel extends javax.swing.JPanel {

    /**
     * Creates new form AboutPanel
     */
    public AboutPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        ttPanel = new javax.swing.JPanel();
        ttL = new javax.swing.JLabel();
        aiPanel = new javax.swing.JPanel();
        aiL = new javax.swing.JLabel();
        acPanel = new javax.swing.JPanel();
        acL = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();
        Label8 = new javax.swing.JLabel();
        Label9 = new javax.swing.JLabel();
        Label10 = new javax.swing.JLabel();

        Label1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        Label1.setForeground(new java.awt.Color(0, 153, 51));
        Label1.setText("Bangladesh University of Engineering & Technology");

        Label2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        Label2.setForeground(new java.awt.Color(0, 153, 0));
        Label2.setText("CSE-202 Term Project");

        Label3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        Label3.setForeground(new java.awt.Color(0, 0, 255));
        Label3.setText("Project Superviser - Dr. Anindya Iqbal");

        ttL.setText(" ");

        javax.swing.GroupLayout ttPanelLayout = new javax.swing.GroupLayout(ttPanel);
        ttPanel.setLayout(ttPanelLayout);
        ttPanelLayout.setHorizontalGroup(
            ttPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ttPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ttL)
                .addContainerGap())
        );
        ttPanelLayout.setVerticalGroup(
            ttPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ttPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ttL)
                .addContainerGap())
        );

        ImageIcon tt = new ImageIcon("ReSource\\MultiMedia\\Images\\"
            + "Others\\TT.jpg");
        ttL.setIcon(tt);

        aiL.setText(" ");

        javax.swing.GroupLayout aiPanelLayout = new javax.swing.GroupLayout(aiPanel);
        aiPanel.setLayout(aiPanelLayout);
        aiPanelLayout.setHorizontalGroup(
            aiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aiL)
                .addContainerGap())
        );
        aiPanelLayout.setVerticalGroup(
            aiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aiL)
                .addContainerGap())
        );

        ImageIcon ai = new ImageIcon("ReSource\\MultiMedia\\Images\\"
            + "Others\\AI.jpg");
        aiL.setIcon(ai);

        acL.setText(" ");

        javax.swing.GroupLayout acPanelLayout = new javax.swing.GroupLayout(acPanel);
        acPanel.setLayout(acPanelLayout);
        acPanelLayout.setHorizontalGroup(
            acPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(acL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        acPanelLayout.setVerticalGroup(
            acPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(acL)
                .addContainerGap())
        );

        ImageIcon ac = new ImageIcon("ReSource\\MultiMedia\\Images\\"
            + "Others\\AC.jpg");
        acL.setIcon(ac);

        Label4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        Label4.setForeground(new java.awt.Color(102, 0, 0));
        Label4.setText("Developers");

        Label5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Label5.setText("Tarik Reza Toha");

        Label6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Label6.setText("S201205082");

        Label7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Label7.setText("tarik.toha@gmail.com");

        Label8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Label8.setText("Amit Chakraborty");

        Label9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Label9.setText("S201205086");

        Label10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Label10.setText("amitchakraborty074@gmail.com");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(Label2))
                            .addComponent(Label1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ttPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(aiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(acPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(Label3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label5)
                                    .addComponent(Label6)
                                    .addComponent(Label7))
                                .addGap(256, 256, 256)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label9)
                                    .addComponent(Label10)
                                    .addComponent(Label8)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(Label4)))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Label1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label2)
                        .addGap(15, 15, 15)
                        .addComponent(Label3)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ttPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(Label4)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label5)
                    .addComponent(Label8))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label6))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label7)
                    .addComponent(Label10))
                .addGap(259, 259, 259))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel Label9;
    private javax.swing.JLabel acL;
    private javax.swing.JPanel acPanel;
    private javax.swing.JLabel aiL;
    private javax.swing.JPanel aiPanel;
    private javax.swing.JLabel ttL;
    private javax.swing.JPanel ttPanel;
    // End of variables declaration//GEN-END:variables
}
